.\" Manpage for topgrade.
.\" Contact github/Linux4Life531 to correct errors or typos.
.TH man 8 "22 Febuary 2020" "1.0" " Topgrade Manpage"
.SH NAME
topgrade - upgrade everything on your computer
.SH SYNOPSIS
topgrade - updates everything
.SH DESCRIPTION
Keeping your system up to date mostly involves invoking more than a single package manager. This usually results in big shell one-liners saved in your shell history. Topgrade tries to solve this problem by detecting which tools you use and run their appropriate package managers.
.SH OPTIONS
topgrade does not take any options.
.SH BUGS
For a list of bugs see https://github.com/r-darwish/topgrade/issues.
.SH AUTHOR
James Ashwood (To contact I'm at github/Linux4Life531)
